kafka:
  bootstrap-servers: dummy
  batch-message:
    topic: test-topic
    group-id: test-topic.0
    enable-auto-commit: false
    max-poll-records: 10
    fetch-min-bytes: 1024
    fetch-max-wait-ms: 1000
    poll-duration-ms: 1000
  single-message:
    topic: test-topic
    group-id: test-topic.1
    enable-auto-commit: true
    auto-commit-interval-ms: 1000
    max-poll-records: 1
    poll-duration-ms: 1000
  example-event:
    topic: test-topic
    acks: "all"
    retries: 3
    enable-idempotence: true
