server:
  port: 9193

spring:
  docker:
    compose:
      enabled: false

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}
  schema-registry-url: ${SCHEMA_REGISTRY_URL}
  app-id: 1a2489e64a2c
  blocked-user:
    topic: blocked-user
  private-message:
    topic: private-message
  censored-message:
    topic: censored-message

banned-words:
  # базовые формы слов, голубь -> голуб, площадь -> площад
  root: голуб, площад

logging.level.org.springframework.web: trace
