version: '3.8'

networks:
  kafka-net:
    driver: bridge
    name: kafka-cluster-network

services:
  kafka-practicum-yandex:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    networks:
      - kafka-net
    environment:
      BOOTSTRAP_SERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
    deploy:
      mode: replicated
      replicas: 2
